name: Pre-commit
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5

      - id: pre-commit
        name: Pre Commit
        uses: pre-commit/action@v3.0.1

      - name: Generate patch
        if: ${{ failure() && steps.pre-commit.conclusion == 'failure' }}
        run: |
          git diff > patch.diff

      - name: Upload Patch
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        if: ${{ failure() && steps.pre-commit.conclusion == 'failure' }}
        with:
          name: patch
          path: ./patch.diff

      - name: Apply Patch Instruction
        if: ${{ failure() && steps.pre-commit.conclusion == 'failure' }}
        run: |
          echo 'Run the command `pre-commit` or download the patch file at the following URL:'
          echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}${PR:+?pr=$PR}#artifacts"
        env:
          PR: ${{ github.event.pull_request.number }}
